### PR TITLE
added hal lib to project file

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RoboDurden** [comment]
Sorry i do not see the "requested" code changes to the target.h file.

**Comment by AILIFE4798** [comment]
now back to 36 error and no error for 2.6 layout

**Comment by AILIFE4798** [comment]
i have included the hal .h files in target compile option

**Comment by AILIFE4798** [comment]
i dont know why the rte components.h is changed i did not do that its done automaticly

**Comment by RoboDurden** [comment]
i would like to see a proof that the new hal files are actually used in the main code.
Therefore please add to target.h and hit F7:
```

#ifdef GD32E230
	#include "gd32e23x.h"
	#define TARGET_nvic_irq_enable(a, b, c){nvic_irq_enable(a, b);}
	#define TARGET_nvic_priority_group_set(a)	// that function does not exist for this target = not needed ?
	#define TARGET_adc_vbat_disable()
#elif defined MM32SPIN05	
	
	#include "MM32_HAL/hal_conf.h"
	void TIM2_IRQHandler(void)	// just for testing
	{
			TIM_ClearITPendingBit(TIM2, TIM_IT_Update);		// fine, now TIM_IT_Update is defined
	}

	#include "mm32_device.h"

	#include "MM32_HAL/hal_device.h"
	#include "MM32_HAL/hal_rcc.h"
```

**Comment by AILIFE4798** [comment]
it created allot more error unfortunately but it did not say library not found
image

**Comment by AILIFE4798** [comment]
i have moved the library to device folder now so no need for ```#include "MM32_HAL/hal_device.h"```

**Comment by AILIFE4798** [comment]
commented out the redefinition in define_2.8.h and back to 36 error so it worked
image

**Comment by RoboDurden** [comment]
the redefenition errors in defines_2-8.h can easily be removed:
```

/*
// found in hal_tim.h of MM32SPIN0x_q_Samples
typedef enum {
    TIM_Channel_1 = 0x0000,  ///< TIM Channel 1
    TIM_Channel_2 = 0x0004,  ///< TIM Channel 2
    TIM_Channel_3 = 0x0008,  ///< TIM Channel 3
    TIM_Channel_4 = 0x000C,  ///< TIM Channel 4
    TIM_Channel_5 = 0x0010   ///< TIM Channel 5
} TIMCHx_Typedef;
*/
```

That dirty code is no longer needed :-)

**Comment by AILIFE4798** [comment]
yeah i have commented out and commited change

**Comment by RoboDurden** [comment]
But i have these nasty 

`Inc/MM32_HAL/hal_rcc.c(292): error: use of undeclared identifier 'RCC_CFGR_SWS_HSI'
`
errors

Because the reg_rcc.h thas i found in the examples folder C:\Projects Keil\MM32SPIN0x_q_Lib_Samples\Device\MM32SPIN0x_q\Include\reg_rcc.h

 is different from the reg_rcc.h that we have installed with the packet manager: C:\Users\PAN CF-LX6\AppData\Local\Arm\Packs\MindMotion\MM32SPIN0x_DFP\1.0.8\Device\MM32SPIN06xx_s\Include\reg_rcc.h

So i fear the this hal library is not compatible with our packet installaition.

Do you also get these errors ??

**Comment by RoboDurden** [comment]
This is telling me that for some reason your requested changes to target.h are not in effect:

```
Src/it.c(117): error: use of undeclared identifier 'TIMER_INT_UP'
  117 |         timer_interrupt_flag_clear(TIMER_TIMEOUT, TIMER_INT_UP);
```

I got rid of this error because of `#include "MM32_HAL/hal_conf.h"`

**Comment by AILIFE4798** [comment]
i have moved the hal files to \Device\MM32SPIN0x_q\HAL_Lib\Src because you say you wanted it there
image
and included it in here
so i can solve the error

**Comment by AILIFE4798** [comment]
because otherwise the 2.6 will also try to compile those file and wont work any more

**Comment by RoboDurden** [comment]
I am really glad you do all this work.
But i want to be sure that the pull request is really moving the project forward.
So that the example code like Timer2BacisExample compiles nicely within our Gen2

**Comment by AILIFE4798** [comment]
yeah i can understand
i am human and makes mistake
its better to verify it

**Comment by RoboDurden** [comment]
Please also understand that i did not really create this project. It is a fork from a fork.
So by now even you have better understanding of Keil then i do have.
So if you add changes that make the entire project fail
i will not be able to repair it.
That is why i am very anxious to accept such a massive pull request.

**Comment by AILIFE4798** [comment]
at least you can revert back to last stable version in github
wont be the end of this project
i have comfirmed 2.6 still compile but gd32e does not and its not due to this change
i have tried to revert twice only to find it is normal to not compile i did not break it

**Comment by AILIFE4798** [comment]
although you did not created this project but you understand the entire code structure already while i have not looked into the actual code i just figuring out how to add new target etc

**Comment by RoboDurden** [comment]
Yes, GD32E230 is not compiling because i still had not the time to conert the defines_2-7.h to the new PA6 defines.
So i 2.6 is still compiling, i am happy.
and if your

```
Src/it.c(117): error: use of undeclared identifier 'TIMER_INT_UP'
  117 |         timer_interrupt_flag_clear(TIMER_TIMEOUT, TIMER_INT_UP);
```
is gone.

Then your pull request should be an improvement to what i so far have achieved

When do you sleep ???
What time is it at your place ?
You must be living in the east of China to be still awake.

**Comment by AILIFE4798** [comment]
yes
if you are concerned just clone my repo to somewhere else and test first
i didnt try to break your project i really want to make it better

its 1.30 am here as a programmer its normal to still be awake

**Comment by RoboDurden** [comment]
unfortunately i can not fork your fork because i already host the original.
And downloading the zip always fails  somwhere from 50 MB to 150 MB. Don't know why.
I do not have the best internet connection. 600 kB/s

**Comment by AILIFE4798** [comment]
i thought china have the worst internet in the world but aparently its not true
the repo is quite large so not the easiest to download 
maybe install github desktop client would helps

**Comment by AILIFE4798** [comment]
i think it may be internet problem try using vpn its how we solve these things in china

unfortunately i still have the error at it.c at line 117 i think i need to include some other file
i am not quite sure but the test function in target.h worked so i assume it worked
maybe create another github account to fork my repo would be last resort

its 3 am now i will solve these tomorrow
gn

**Comment by RoboDurden** [comment]
Okay my fault !
The complete MM32 code in target.h must be

```
#elif defined MM32SPIN05	

	#include "MM32_HAL/hal_conf.h"
	void TIM2_IRQHandler(void)	// just for testing
	{
			TIM_ClearITPendingBit(TIM2, TIM_IT_Update);		// fine, now TIM_IT_Update is defined
}


	#include "mm32_device.h"

	#include "MM32_HAL/hal_device.h"
	#include "MM32_HAL/hal_rcc.h"

	#define timer_interrupt_flag_clear TIM_ClearITPendingBit
	#define TIMER_INT_UP TIM_IT_Update
	
	#define ErrStatus ErrorStatus
	
	/* GPIO pin definitions */
	#define GPIO_PIN_0                 BIT(0)                /*!< GPIO pin 0 */
	#define GPIO_PIN_1                 BIT(1)                /*!< GPIO pin 1 */
	#define GPIO_PIN_2                 BIT(2)                /*!< GPIO pin 2 */
	#define GPIO_PIN_3                 BIT(3)                /*!< GPIO pin 3 */
	#define GPIO_PIN_4                 BIT(4)                /*!< GPIO pin 4 */
	#define GPIO_PIN_5                 BIT(5)                /*!< GPIO pin 5 */
	#define GPIO_PIN_6                 BIT(6)                /*!< GPIO pin 6 */
	#define GPIO_PIN_7                 BIT(7)                /*!< GPIO pin 7 */
	#define GPIO_PIN_8                 BIT(8)                /*!< GPIO pin 8 */
	#define GPIO_PIN_9                 BIT(9)                /*!< GPIO pin 9 */
	#define GPIO_PIN_10                BIT(10)               /*!< GPIO pin 10 */
	#define GPIO_PIN_11                BIT(11)               /*!< GPIO pin 11 */
	#define GPIO_PIN_12                BIT(12)               /*!< GPIO pin 12 */
	#define GPIO_PIN_13                BIT(13)               /*!< GPIO pin 13 */
	#define GPIO_PIN_14                BIT(14)               /*!< GPIO pin 14 */
	#define GPIO_PIN_15                BIT(15)               /*!< GPIO pin 15 */
	#define GPIO_PIN_ALL               BITS(0,15)            /*!< GPIO pin all */
	
#else
```

You do not yet have

	#define timer_interrupt_flag_clear TIM_ClearITPendingBit
	#define TIMER_INT_UP TIM_IT_Update

in your pull request which is needed to map the 

`	timer_interrupt_flag_clear(TIMER_TIMEOUT, TIMER_INT_UP);
`

in it.c:117 to the HAL syntax.

My fault :-(
Please add the above to your target.h, then the 

```
Src/it.c(117): error: use of undeclared identifier 'TIMER_INT_UP'
  117 |         timer_interrupt_flag_clear(TIMER_TIMEOUT, TIMER_INT_UP);
```

should be gone and this line not showing any errors any more.

**Comment by RoboDurden** [comment]
Sleep well.
Do not spend too much time on this Gen2.x repo.
This Gen2.x will not save the world !
my masterplan could save the world. But nobody cares :,(

**Comment by AILIFE4798** [comment]
I will test adding the define later
Had some things to do irl(yeah, programmer having a real life)
I also want to share that I found another seller selling a new layout and it is for$1 but he only sell the slave board no master so we will have to modify it but it's gd32 c8t6 so it can support foc and it have dedicated driver ic
Screenshot_2024-01-09-16-36-29-279_com taobao taobao~2
Maybe you can consider

**Comment by AILIFE4798** [comment]
It is same price because I have to buy 2 to control 2 motor
One is gd32 64kb but I have to deal with the missing power circuit on slave
Other one is complete set but I need to find my own cable and I also need to make mm32 work

**Comment by RoboDurden** [comment]
Good morning :-)
This slave board is quite close to https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/tree/main/Schematics_2.3
If the master slave header is only +5V, then the slave should be able to be powered only with this 5V, which is not such a big deal all ESP32/Arduino modules can also be powered with 5V.
If the positive voltage on the master-slave uart header is 15V, it would be less nice.
But as this slave board has a 6x gate driver chip which might generate the +15V gate voltages itself, the board might indeed only need 5V to startup.
With two sot-8 dual opamp it probably will have low-side current sensing and therefore capable of FOC.

I wonder if we could run a $2000 Kickstarter with $2 for a board. Plus shipping :-/ 
But i guess these super cheap offers are only remaining stock / remnants :-(

So it might be better to have bigger project where we need 2000 motor controllers ourselves.
I would like to build the version 2 of my solar car this year.. With a frame made of bamboo and 4 direct driven hoverboard wheels.. So for a Kickstarter with 500 of these bamboo hover cars, we would need 2000 motor controllers.

I have already build a  prototype to test the steering mechanismn.
And bought 100 bamboo sticks of length 274 cm, 18-20mm thickness for USD 235 ..

But bamboo sticks should be cheaper in China and building a car frame of bamboo requieres a lot hand work.
Building such a bamboo hover car might be better in China.
If you are interested or know someone who would like to start a company for this, feel free to send me an email to roland@robo4future.de

**Comment by AILIFE4798** [comment]
i guess the board requires 15v at least my layout2.6 does
the bigger problem is most buck regulator like lm2596 can only handle max 36v and a fully charged battery is 42v so they wont work
i do think these will support the gen1 foc firmware because of the gd32
these especially the slave only is defnately manufacture cerplus so not a sustainable source for them
but more will come up once you bought all of these
but for a product you should still buy the $12 gen1 board
i think at this point sourcing cheap wheels is a larger problem then the controller

**Comment by AILIFE4798** [comment]
image
down to 34 Error now,it Worked

**Comment by RoboDurden** [comment]
Please say when these latest changes are added to this pull request = your fork is up to date.

**Comment by RoboDurden** [comment]
Can you tell me what this new IAR_Core and Keil_Core is needed for ?

**Comment by AILIFE4798** [comment]
i dont know but in the example its also included so i copied all

**Comment by RoboDurden** [comment]
Yes 34 errors :-)
Now i can continue to port the timer syntax..
But even when i get the errors down to zero, this will not mean that the code is actually running :-/
Because only adjusting the gd32 code to compile does not mean there is not additional code missing the MM32 needs to get the job done..


The LM2596HVS can do 60V 3A and is cheap: https://www.aliexpress.com/item/4001360810712.html

**Comment by AILIFE4798** [comment]
did the gd32e one only require syntax change or something is also diferent
because if something is different between gd then mm will be even harder

i will get a few lm2596hvs to see
the hoverboard does not require allot of power so i think one can power 6 main board no problem

**Comment by RoboDurden** [comment]
No, the GD32E230 needed nearly no changes, only

```
#ifdef GD32E230
	#include "gd32e23x.h"
	#define TARGET_nvic_irq_enable(a, b, c){nvic_irq_enable(a, b);}
	#define TARGET_nvic_priority_group_set(a)	// that function does not exist for this target = not needed ?
	#define TARGET_adc_vbat_disable()
```

**Comment by AILIFE4798** [comment]
then i think mm will be doable
the larger problem would be how to unlock and upload firmware because its not documented like gd and stm

**Pull request merged**
