### PR TITLE
EspressLRS support (CRSF decoder)

### PR DESCRIPTION
**Pull request by WizzardDr**
https://cdn.discordapp.com/attachments/596350022191415320/1153628310895599647/VID_20230919_104329.mp4

I added a USART decode mode and made them dependent on `USART_CRSF` or `USART_SERIAL`.

### CODE REVIEW

**Comment by RoboDurden** [comment]
Nice video, good job.
I can not see the uartSteer connection. Do you have such a tiny ExpressLRS module hidden in the setup ?
boot

Now i have a problem with this pull request :-/
And i would be happy if you could move as much as possible of your CRSF code into a new `commsSteeringCRSF.h` file.

I really do not like this non-objectOriented #ifdef chaos of the EFeru FOC Gen1 firmware with all the many `VARIANT_XY`.
Not to say that i hate it.

With my C++ SimpleFOC firmware i go for an abstract base communication (= Pilot) class and begin with a PilotI2c: https://github.com/RoboDurden/Split_Hoverboard_SimpleFOC/blob/main/include/PilotI2c.h

Here with the C firmware, this is not possible.
I think the closed way to a base class and dervied control/pilot classes would be

`commsSteering.h` containing the TEST_SPEED functionality
`commsSteeringUART.h` have the current uart code
`commsSteeringSRSV.h` with your new code

Users already request PWM and ADC control :-(

All three files share the same function definitions so there is no more need for stupid `#ifdef TEST_SPEED` etc.

The `main.c: while(1)` loop would call a function `CommsSteeringUpdate()`
Only the `commsSteering.h` would then execute the TEST_SPEED code while the other two function implementations would instantly return because they change speed and steer interrupt driven.

If you understand the idea, i would be happy if you would change your code because i can not test it.
But this is not a must.
I am happy for the code you are contributing with this pull request.
So i also could transform your code, push my changes and you update your fork to verify my changes.

Ideas welcome.

**Comment by RoboDurden** [comment]
Okay i will do the design changes. But not today.
There are other users working with different layouts right now so when i accept your pull request i feel the pressure to quickly get your CRSF specific code out of the way.

When if have made the design change to allow different controllers/pilots (always only one so no mixing) it would be great if you make a youtube video tutorial on which parts to buy to user your controll method :-)

What do you think of my idea to name these different controllers "pilots" ?
English is not my native language..

**Comment by WizzardDr** [comment]
commsSteeringCRSF.h

Could also have proxies for telemetry.

Maybe make a /inputs directory in /src for all the input type files.

**Comment by WizzardDr** [comment]
commsSteeringCRSF.h

Could also have proxies for telemetry.

Maybe make a /inputs directory in /src for all the input type files.

**Comment by WizzardDr** [comment]
I am looking at the inputs a devices rather than the person. So using maybe an encoder via an arduino for a steering wheel while using an adc input for a throttle, and having the option to connect a pwm rc remote with an override switch for remote control. So I think pilots would be to restrictive of a concept.

I think people's use could cases vary a lot from just a speed and steering input.

For example alongside the remote input I am going to have a autonomous controller loop with a camera so the wheel speed will be controlled 1 to 1 so the kinematics can be calculated for the control.

**Comment by RoboDurden** [comment]
Well i really love object orientend programming, one of the most important inventions of last century. More important than the invention of the car or the atomic bomb !
So i always think of objects as persons of a big team who do their job to make the big thing running - like being a pilot.
From the perspective of the hoverboard-board (with the commsMasterSlave), it is rather only about speed left and speed right.
So some "person" is needed to tell the hardware the speedL and speedR. That person would pilot the hardware.
But yes, a tank would need speedL and speedR and a car would need speed and steer.
My log band saw takes distance forward-backward and distance up/down.

But for more complex situations (like vision control), we need an additional ESP32 anyway ?
So again from the perspective of this firmware, the uart communication is the pilot.

Maybe "operator" would also work.
But i do not like these generic words like operator or controller becasue they can mean so many things.
The hardware is already called hoverboard controller :-(

So introducing the concept of a pilot should make it easier to understand where functionality belongs..

**Comment by RoboDurden** [comment]
Of course, the Arduino code could also have its own Pilot class that implements the vision control and sends speed steer commands to the hoverboard.
But inside the hoverbaord firmware threre would only be the pilot without vision control who gets his idea for speed and steer via uart..

I aggree that there should be a third class in between the uart and the motor: Receiver (uart) -> Pilot (data to speed/steer or speedL/speedR) -> Motors.
Problem is that the receivers protocol already contains the info whether it is speed/steer or speedL/speedR.

So Receiver -> Pilot -> Motor is not that easy to implement.

Problem with "receiver" also is, that commsSteering does not only receive but also transmits data back to the Arduino.

So i prefer to think of that receiver als the pilot and do not care who is piloting the pilot from the Arduino/Esp32/RC-Control/etc.

The pilot is the one who comes up with the speed/steer values.

**Comment by WizzardDr** [comment]
What hardware does simpleFoc need that isn't the 64kb MCU?

I have got some simpleFOCMini that I am yet to use on a fast processor, I have made a custom foc controller / sine closed loop controller with gimbal motor and 3half bridges but it needs more voltage to overcome cogging.

I really don't think it needs to be c++ due to the lack of instancing.

**Comment by RoboDurden** [comment]
The layouts with a GD32130C6 MCU only have 32 kB. Our SimpleFOC firmware currently needs 43764 bytes :-(

**Comment by WizzardDr** [comment]
Oh, I miss read, you mean the foc firmware will run on 64kb... so the Gen2.x will have no use.

**Comment by WizzardDr** [comment]
I look forward to testing it... hopefully it should help tight the path following control loop I intend to get working.

**Comment by Jim13MC** [comment]
WizzardDr what is your YouTube channel? I am interested in the video you mentioned that you could make.

**Pull request merged**
